### ISSUE TITLE
wrapt installation

### ISSUE THREAD

**Issue by sancoder** [Blockstream/blind_pin_server#29]
While installing requirements for personal blind server on a system with Python 3.11 installation fails with
`pip install --require-hashes -r requirements.txt`

```
[skip]
Collecting wrapt==1.13.3 (from -r requirements.txt (line 46))
  Using cached wrapt-1.13.3.tar.gz (48 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [85 lines of output]
      Traceback (most recent call last):
        File "/tmp/pip-build-env-p5th1z7r/overlay/lib/python3.11/site-packages/setuptools/config/expand.py", line 80, in __getattr__
          return next(
                 ^^^^^
        File "/tmp/pip-build-env-p5th1z7r/overlay/lib/python3.11/site-packages/setuptools/config/expand.py", line 81, in <genexpr>
          ast.literal_eval(value)
        File "/usr/lib/python3.11/ast.py", line 110, in literal_eval
          return _convert(node_or_string)
                 ^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3.11/ast.py", line 109, in _convert
          return _convert_signed_num(node)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3.11/ast.py", line 83, in _convert_signed_num
          return _convert_num(node)
                 ^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3.11/ast.py", line 74, in _convert_num
          _raise_malformed_node(node)
        File "/usr/lib/python3.11/ast.py", line 71, in _raise_malformed_node
          raise ValueError(msg + f': {node!r}')
      ValueError: malformed node or string on line 2: <ast.Call object at 0x7fecb1466b60>
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "/tmp/pip-build-env-p5th1z7r/overlay/lib/python3.11/site-packages/setuptools/config/expand.py", line 192, in read_attr
          return getattr(StaticModule(module_name, spec), attr_name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-p5th1z7r/overlay/lib/python3.11/site-packages/setuptools/config/expand.py", line 86, in __getattr__
          raise AttributeError(f"{self.name} has no attribute {attr}") from e
      AttributeError: wrapt has no attribute __version__
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/home/user/jade-pinserver/venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/user/jade-pinserver/venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/user/jade-pinserver/venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-p5th1z7r/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 366, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/tmp/pip-build-env-p5th1z7r/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-p5th1z7r/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 41, in <module>
        File "/tmp/pip-build-env-p5th1z7r/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 104, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-p5th1z7r/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 159, in setup
          dist.parse_config_files()
        File "/tmp/pip-build-env-p5th1z7r/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 627, in parse_config_files
          setupcfg.parse_configuration(
        File "/tmp/pip-build-env-p5th1z7r/overlay/lib/python3.11/site-packages/setuptools/config/setupcfg.py", line 190, in parse_configuration
          meta.parse()
        File "/tmp/pip-build-env-p5th1z7r/overlay/lib/python3.11/site-packages/setuptools/config/setupcfg.py", line 501, in parse
          section_parser_method(section_options)
        File "/tmp/pip-build-env-p5th1z7r/overlay/lib/python3.11/site-packages/setuptools/config/setupcfg.py", line 476, in parse_section
          self[name] = value
          ~~~~^^^^^^
        File "/tmp/pip-build-env-p5th1z7r/overlay/lib/python3.11/site-packages/setuptools/config/setupcfg.py", line 294, in __setitem__
          parsed = self.parsers.get(option_name, lambda x: x)(value)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-p5th1z7r/overlay/lib/python3.11/site-packages/setuptools/config/setupcfg.py", line 593, in _parse_version
          return expand.version(self._parse_attr(value, self.package_dir, self.root_dir))
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-p5th1z7r/overlay/lib/python3.11/site-packages/setuptools/config/setupcfg.py", line 418, in _parse_attr
          return expand.read_attr(attr_desc, package_dir, root_dir)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-p5th1z7r/overlay/lib/python3.11/site-packages/setuptools/config/expand.py", line 195, in read_attr
          module = _load_spec(spec, module_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-p5th1z7r/overlay/lib/python3.11/site-packages/setuptools/config/expand.py", line 215, in _load_spec
          spec.loader.exec_module(module)  # type: ignore
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap_external>", line 940, in exec_module
        File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
        File "/tmp/pip-install-h5poq39t/wrapt_e7289b3e77234a82a1eb555ef4cc5e27/src/wrapt/__init__.py", line 10, in <module>
          from .decorators import (adapter_factory, AdapterFactory, decorator,
        File "/tmp/pip-install-h5poq39t/wrapt_e7289b3e77234a82a1eb555ef4cc5e27/src/wrapt/decorators.py", line 34, in <module>
          from inspect import ismethod, isclass, formatargspec
      ImportError: cannot import name 'formatargspec' from 'inspect' (/usr/lib/python3.11/inspect.py)
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.
```

Found this bug https://github.com/GrahamDumpleton/wrapt/issues/196
They say that it's fixed in wrapt 1.14.0

**Comment by JamieDriver** [comment]
Update to latest version (`1.16.0`) in master.
Apologies for the delay!
